board/urls.py
from django.urls import path

from . import views

app_name='board'

urlpatterns = [
    path('', views.index, name='index'),
    path('board/about_site/', views.about_site, name='about_site'),
    path('board/signup/', views.signup, name='signup'),
    path('board/signup/username_check/', views.username_check, name='username_check'),
    path('board/signup_success/', views.signup_success, name='signup_success'),
    path('board/signup_process/', views.signup_process, name='signup_process'),
    path('board/signup_fail/<str:error>/', views.signup_fail, name='signup_fail'),
    path('board/signin/', views.signin, name='signin'),
    path('board/signin_process/', views.signin_process, name='signin_process'),
    path('board/signin_success/', views.signin_success, name='signin_success'),
    path('board/signin_need/', views.signin_need, name='signin_need'),
    path('board/signin_fail/', views.signin_fail, name='signin_fail'),
    path('board/idea_list/', views.idea_list, name='idea_list'),
    path('board/idea_list/add_comment', views.add_comment, name='add_comment'),
    path('board/idea_list/delete_comment', views.delete_comment, name='delete_comment'),
    path('board/idea_list/update_comment', views.update_comment, name='update_comment'),
    path('board/idea_list/likes_process/', views.likes_process, name='likes_process'),
    path('board/idea_new/', views.idea_new, name='idea_new'),
    path('board/idea_delete/<int:pk>', views.idea_delete, name='idea_delete'),
    path('board/idea_edit/<int:pk>/', views.idea_edit, name='idea_edit'),
    path('board/logout_process/', views.logout_process, name='logout_process'),
    path('board/logout_success/', views.logout_success, name='logout_success'),
    path('board/about_user/', views.about_user, name='about_user'),
    path('board/about_user/user_update/', views.user_update, name='user_update'),
    path('board/about_user/user_update_success/', views.user_update_success, name='user_update_success'),
    path('board/about_user/user_update_fail/<str:error>', views.user_update_fail, name='user_update_fail'),
    path('board/about_user/user_update_process/', views.user_update_process, name='user_update_process'),
    path('board/about_user/user_idea/', views.user_idea, name='user_idea'),
    path('board/about_user/user_likes/', views.user_likes, name='user_likes'),
    path('board/application/', views.application, name='application'),
    path('board/feedback/', views.feedback, name='feedback'),
    path('board/motivation/', views.motivation, name='motivation'),
]

weneedthis/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as mail_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('email/', include(mail_urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from ckeditor_uploader.fields import RichTextUploadingField



class User(AbstractUser):
    thinker_likes=models.IntegerField(default=0)
    thinker_status=models.CharField(max_length=20,default='꿈나무')

    def __str__(self):
        return self.username

    def update_thinker_status(self):
        if self.thinker_likes>19:
            self.thinker_status='혁신가'
            self.save()
        else:
            self.thinker_status='꿈나무'
            self.save()

    @property
    def total_ideas(self):
        return self.idea.count()

    @property
    def total_ideas_likes(self):
        return self.idea_likes.count()
    
    @property
    def total_comments(self):
        return self.comment.count()

    @property
    def total_comments_likes(self):
        return self.comment_likes.count()
    

class form(models.Model):
    article=RichTextUploadingField()
    pub_date=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True
        ordering=['-pub_date']


class Idea(form):
    author=models.ForeignKey('User',on_delete=models.CASCADE,related_name='idea')
    title=models.CharField(max_length=100)
    likes=models.ManyToManyField('User',related_name='idea_likes',blank=True)
 
    def __str__(self):
        return self.author.username+' - '+self.title

    @property
    def total_likes(self):
        return self.likes.count() 

class Motivation(form):
    author=models.ForeignKey('User',on_delete=models.CASCADE,related_name='motivation')
    title=models.CharField(max_length=100)
    likes=models.ManyToManyField('User',related_name='motivation_likes',blank=True)

    def __str__(self):
        return self.author.username+' - '+self.title

    @property
    def total_likes(self):
        return self.likes.count() 




class form2(models.Model):
    article=models.TextField()
    pub_date=models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract=True
        ordering=['pub_date']



class Comment(form2):
    for_idea=models.ForeignKey('Idea',on_delete=models.CASCADE,related_name='comment')
    reply_to=models.ForeignKey('self',on_delete=models.CASCADE,related_name='replies',blank=True,null=True)
    author=models.ForeignKey('User',on_delete=models.CASCADE,related_name='comment')
    likes=models.ManyToManyField('User',related_name='comment_likes',blank=True)

    def __str__(self):
        return self.author.username+' - '+self.article

    @property
    def total_likes(self):
        return self.likes.count()


class Message(form2):
    sender=models.ForeignKey('User',on_delete=models.CASCADE,related_name='send_message')
    receiver=models.ForeignKey('User',on_delete=models.CASCADE,related_name='receive_message')

    def __str__(self):
        return 'sender:'+self.sender.username+', receiver:'+self.receiver.username+' - '+self.article

board/forms.py
from django import forms
from .models import User,Idea,Comment
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class IdeaForm(forms.ModelForm):
    class Meta:
        model=Idea
        fields=['title','article']
        widgets={
            'article': forms.CharField(widget=CKEditorUploadingWidget()),
        }

board/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from .models import User,Idea,Comment,Message
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.hashers import check_password
import json
from .forms import IdeaForm
from django_email_verification import sendConfirm
from django.template.loader import render_to_string


def index(request):
    return render(request,'board/index.html')

def about_site(request):
    return render(request,'board/about_site.html')

@login_required
def idea_list(request):
    form=Idea.objects.all()
    user=request.user
    return render(request,'board/idea_list.html',{'form':form,'user':user})

@login_required
def likes_process(request):
    idea=Idea.objects.get(pk=request.POST['pk'])
    user=request.user

    if idea.likes.filter(id=user.id).exists():
        idea.likes.remove(user)
        idea.author.thinker_likes-=1
        idea.author.save()
        flag=False
    else:
        idea.likes.add(user)
        idea.author.thinker_likes+=1
        idea.author.save()
        flag=True

    message=idea.likes.count()
    context={'message':str(message)+'명','flag':flag}
    return HttpResponse(json.dumps(context),content_type='application/json')


@login_required
def idea_delete(request,pk):
    idea=Idea.objects.get(pk=pk)
    idea.delete()
    return redirect('board:idea_list')

@login_required
def idea_new(request):
    if request.method=="POST":
        form=IdeaForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('board:idea_list')
    else:
        form = IdeaForm()
    return render(request,'board/idea_edit.html',{'form':form})

@login_required
def idea_edit(request,pk):
    post = get_object_or_404(Idea, pk=pk)
    user=request.user
    if post.author==user:
        if request.method == "POST":
            form = IdeaForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                return redirect('board:idea_list')
        else:
            user=request.user
            form = IdeaForm(instance=post)
        return render(request,'board/idea_edit.html',{'form':form,'post':post})
    else:
       return render(request,'board/idea_detail.html',{'post':post}) 

def signin(request):
    return render(request,'board/signin.html')

def signin_fail(request):
    return render(request,'board/signin_fail.html')

def signin_success(request):
    return render(request,'board/signin_success.html',{'username':request.user.username})

def signin_need(request):
    return render(request,'board/signin_need.html')

def signin_process(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        user=request.user
        user.update_thinker_status()
        if request.POST.get('remember'):
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE=False
        else:
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE=True
        
        return HttpResponseRedirect(reverse('board:signin_success'))
    else:
        # Return an 'invalid login' error message.
        return HttpResponseRedirect(reverse('board:signin_fail'))






def signup(request):
    return render(request,'board/signup.html')

def signup_fail(request,error):
    return render(request,'board/signup_fail.html',{'error':error})

def signup_success(request):
    return render(request,'board/signup_success.html')

def signup_process(request):
    try: 
        User.objects.get(username=request.POST['username'])
        return HttpResponseRedirect(reverse('board:signup_fail',args=('username',)))  
    except:
        username=request.POST['username']

    if request.POST['password']!=request.POST['confirm']:
        return HttpResponseRedirect(reverse('board:signup_fail',args=('password',))) 
    password= request.POST['password']
    email=request.POST['email']
    # Add session!!
    user=User.objects.create_user(username=username,password=password,email=email)
    sendConfirm(user)
    return HttpResponseRedirect(reverse('board:signup_success')) 

def logout_process(request):
    logout(request)
    return HttpResponseRedirect(reverse('board:logout_success'))

def logout_success(request):
    return render(request,'board/index.html')

def user_update(request):
    return render(request,'board/user_update.html')

def user_update_process(request):
    if check_password(request.POST['origin_password'],request.user.password):
        if request.POST['password']=='':
            user=User.objects.get(username=request.user.username)
            user.email=request.POST['email']
            user.save()
            return HttpResponseRedirect(reverse('board:user_update_success'))
        else:
            if request.POST['password']!=request.POST['confirm']:
                return HttpResponseRedirect(reverse('board:user_update_fail',args=('새 비밀번호',))) 
            else:
                user=User.objects.get(username=request.user.username)
                user.email=request.POST['email']
                user.set_password(request.POST['password'])
                user.save()
                login(request,user)
                return HttpResponseRedirect(reverse('board:user_update_success')) 
    else:
        return HttpResponseRedirect(reverse('board:user_update_fail',args=('기존 비밀번호',))) 

def user_update_success(request):
    return render(request,'board/user_update_success.html')

def user_update_fail(request,error):
    return render(request,'board/user_update_fail.html',{'error':error})

def username_check(request):
   
    try:
        User.objects.get(username=request.POST['pk'])
        message='동일한 아이디가 존재합니다.'
    except:
        if request.POST['pk']=='':
            message='아이디를 입력해주세요.'
        else:
            message='가능한 아이디입니다!'
    
    context={'message':message}
    return HttpResponse(json.dumps(context),content_type='application/json')

def about_user(request):
    user=request.user
    return render(request,'board/about_user.html',{'user':user})

def user_idea(request):
    user=request.user
    return render(request,'board/user_idea.html',{'user':user})

def user_likes(request):
    user=request.user
    return render(request,'board/user_likes.html',{'user':user})

def application(request):
    return render(request,'board/application.html')

def feedback(request):
    return render(request,'board/feedback.html')

def motivation(request):
    return render(request,'board/motivation.html')

def add_comment(request):
    idea=Idea.objects.get(pk=request.POST['pk'])
    user=request.user
    comment=Comment.objects.create(for_idea=idea,author=user,article=request.POST['content'])
    html = render_to_string('board/comment_list.html',{'comment':comment,'user':user})

    context={'html':html,'article':comment.article,'author':comment.author.username}
    return HttpResponse(json.dumps(context),content_type='application/json')

def delete_comment(request):
    comment=Comment.objects.get(pk=request.POST['pk'])
    comment.delete()

    context={}
    return HttpResponse(json.dumps(context),content_type='application/json')

def update_comment(request):
    comment=Comment.objects.get(pk=request.POST['pk'])
    comment.article=request.POST['content']
    comment.save()

    context={'article':comment.article}
    return HttpResponse(json.dumps(context),content_type='application/json')

board/templates/board/about_site.html
{% extends './index.html' %}
{% block content%}
<style>
    img{
        width: 100px;
    }
    .starter-template{
        text-align: left;
    }
</style>
{% load static%}
    <div class="starter-template">
        <p>
            이 사이트는 다음과 같은 책에 기인하여 만들어진 사이트입니다.&nbsp;
            <img src="{% static 'img/부의추월차선.jpeg' %}" alt="부의 추월차선(엠제이 드마코 지음)">
            <a href="https://book.naver.com/bookdb/book_detail.nhn?bid=7290748" target="_blank">>>책 자세히 보기</a>
        </p><br>
        <p>
            <h3>Motivation</h3>자기가 생각하는 성공에 도달한 사람은 자신의 성공 스토리를 많은 사람들에게 알려 동기부여를 주고 진심 어린 축하를 받고
            <br>도달하지 못한 사람은 동기부여를 받고 서로 화이팅할 수 있는 카테고리입니다. 
        </p><br>
        <p>
            <h3>Idea & Advice</h3>자신의 기발한 아이디어를 공유해서 팀원을 찾거나 조언을 얻을 수 있는 카테고리입니다.
        </p><br>
        <p>
            <h3>Feedback</h3>이 사이트의 부족한 점이나 필요한 점을 적는 카테고리입니다.
        </p><br>
        <p>
            <h3>랭킹 제도</h3>자신이 쓴 글이나 댓글에 달린 좋아요 개수에 비례하여 랭킹이 상승합니다.
            <div style="border:solid 5px pink; padding:15px;">
                <p>
                    <strong>혁신가</strong>
                    <span>: 좋아요 개수 20개 이상</span>
                </p>
                <p>
                    <strong>꿈나무</strong>
                    <span>: 좋아요 개수 0~19개</span>
                </p>  
            </div>
        </p>
    </div>
<script>
    $('#about').addClass("active");
</script>
{%endblock %}

board/templates/board/about_user.html
{% extends './index.html' %}
{% block content%}
<style>
    .col-md-3 h5{
        color:deepskyblue;
    }
</style>
<div class="row mb-3" style="margin-top: 2rem;">
    <div class="col-md-3 themed-grid-col">
        <a href="{%url 'board:about_user' %}"><h5>내정보</h5></a><br>
        <a href="{%url 'board:user_update' %}"><h5>정보 수정</h5></a><br>
        <a href="{%url 'board:user_idea' %}"><h5>내가 쓴 글</h5></a><br>
        <a href="{%url 'board:user_likes' %}"><h5>내가 누른 좋아요</h5></a><br>
    </div>
    <div class="col-md-9 themed-grid-col text-center">
    {% block article%}
        <h5>현재 랭킹 : {{user.thinker_status}}</h5><br>
        <h5>이메일 : {{user.email}}</h5>
    {%endblock %}
    </div>
    </div>
<script>
    $('#mypage').addClass("active");
</script>
{%endblock %}

   

board/templates/board/comment_list.html
<div class="single_comment" style="margin-top: 10px;">
    &nbsp;
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-return-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M10.146 5.646a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L12.793 9l-2.647-2.646a.5.5 0 0 1 0-.708z"/>
        <path fill-rule="evenodd" d="M3 2.5a.5.5 0 0 0-.5.5v4A2.5 2.5 0 0 0 5 9.5h8.5a.5.5 0 0 0 0-1H5A1.5 1.5 0 0 1 3.5 7V3a.5.5 0 0 0-.5-.5z"/>
    </svg>
    <span style="vertical-align: middle;"><font style="font-weight:600;color:steelblue">{{comment.author}}</font>&nbsp;
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            {%ifequal user comment.author%}
            <button style="font-size: 0.8rem;padding:0.25rem 0.25rem;" type="button" class="btn btn-secondary update" name="{{comment.pk}}" id="update{{comment.pk}}">수정</button>
            <button style="font-size: 0.8rem;padding:0.25rem 0.25rem;" type="button" class="btn btn-secondary delete" name="{{comment.pk}}" id="delete{{comment.pk}}">삭제</button>
            {%endifequal%}
        </div>
    </span><br>
    <div id="comment_article{{comment.pk}}" style="margin-left: 25px;">{{comment.article}}</div>
    <div id="update_article{{comment.pk}}" style="display:none; margin-left: 25px;">
        <div  class="input-group" style=" margin-top: 0.5rem;">
            <input type="text" id="update_comment{{comment.pk}}" class="form-control" value="{{comment.article}}"  aria-describedby="button-addon2">
            <div class="input-group-append">
            <button style="background-color:gainsboro;color:black;"class="btn btn-outline-secondary update_process" type="button" name="{{comment.pk}}" id="update_process{{comment.pk}}">수정</button>
            </div>
        </div>
    </div>
</div>

board/templates/board/feedback.html
{% extends './index.html' %}
{% block content%}
   <h1>Still developing!</h1>
{%endblock %}

board/templates/board/idea_detail.html
{% extends './index.html' %}
{% block content%}
<style>
    h4{
        margin-top:3.5rem;
       
    }
</style>
    <h4 style="word-break: break-all;">{{post.title}}</h4><hr>
    <h6>작성자 : {{post.author}}</h6>
    <div style="word-break: break-all;border:10px solid pink; padding:15px; margin-top: 2rem; margin-bottom: 3rem;">{{post.article|safe}}</div>    
{%endblock %}

board/templates/board/idea_edit.html
{% extends './index.html' %}
{% block content%}
<div class="container">
        <h2 style="margin-top: 2rem;">글쓰기</h2>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" class="btn btn-dark" value="저장">
            {%if post%}
            <a href="{% url 'board:idea_delete' post.pk %}"><input type="button" class="btn btn-dark" value="삭제" style="margin-left: 0.5rem;"></a>
            {%endif%}
        </form>
    </div>
{%endblock %}

board/templates/board/mail_body.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        h1{ color: blue; }
    </style>
</head>
    <body>
        <h1>회원가입이 거의 다 진행됐습니다!</h1><br>
        <h2><a href="{{ link }}">여기</a>를 클릭하시면 회원가입이 완료됩니다.</h2>
    </body>
</html>

board/templates/board/signin_need.html
{% extends './signin.html' %}
{%block err%}
<div style="color:red; text-align: center;">로그인이 필요합니다.</div>
{%endblock%}

board/templates/board/signin_success.html
{% extends './index.html' %}
{% block content%}
<h1 style="text-align: center;">환영합니다, 당신에게 필요한 모든 것을 가져가시길 바랍니다!</h1>
{%endblock %}

board/templates/board/signup_fail.html
{% extends './signup.html' %}

{%block err%}
{%ifequal error 'username' %}
<div style="color:red; text-align: center;">동일한 아이디가 존재합니다.</div>
{%else%}
<div style="color:red; text-align: center;">비밀번호가 일치하지 않습니다.</div>
{%endifequal%}
{%endblock%}

board/templates/board/signup_success.html
{% extends './index.html' %}
{%block content%}

    <h2 style="text-align: center; margin-top:10rem;" id="welcome">회원가입을 완료하기 위해서는 본인 이메일 인증이 필요합니다.</h2><br>
    <h2 style="text-align: center; " id="welcome">인증 메일이 발송되었으니 확인하시길 바랍니다.</h2><br>
 
{%endblock%}

board/templates/board/user_idea.html
{% extends './about_user.html' %}
{% block article%}
<style>
    ul li{
        text-align: left;
    }
</style>
    <p>총 개수 : {{user.total_ideas}}개</p>
    <ul>
    {%for idea in user.idea.all%}
    <li>
        <a href="{% url 'board:idea_edit' idea.pk %}"><h5>{{idea.title}}</h5></a><br>
       
        
    </li>
    {%endfor%}
    </ul>
{%endblock %}

board/templates/board/user_update.html
{% extends './about_user.html' %}
{% block article%}
<style>
    h1{
        margin-top: 0px;
    }
    .form-signin {
  width: 100%;
  max-width: 500px;
  padding: 15px;
  padding-top: 0px;
  margin: auto;
    }
    .form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  display:inline-block;
  width:70%;
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
  margin-left:20px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
</style>
    {% block update_error%}
    {%endblock%}
    <form class="form-signin" action="{% url 'board:user_update_process' %}" method="POST">
        <h4 class="mb-3 font-weight-normal">정보 수정</h4>
        {%csrf_token%}
        <p>
            <span style="margin-right: 11px;">기존 비밀번호</span>
             <label for="inputPassword1" class="sr-only">기존 비밀번호</label>
             <input type="password"  name="origin_password" id="inputPassword1" class="form-control" placeholder="기존 비밀번호" required>
        </p>
        <p>
            <span style="margin-right: 27px;">새 비밀번호</span>
             <label for="inputPassword2" class="sr-only">새 비밀번호</label>
             <input type="password" name="password" id="inputPassword2" class="form-control" placeholder="새 비밀번호" >
             </p>
             <p>
            <span style="margin-right: 11px;">비밀번호 확인</span>
             <label for="inputConfirm" class="sr-only">비밀번호 확인</label>
             <input type="password" name="confirm" id="inputConfirm" class="form-control" placeholder="비밀번호 확인" >
             </p>
             <p>
                 <span style="margin-right: 43px;">새 이메일</span>
                 <label for="inputEmail" class="sr-only">새 이메일</label>
                 <input type="email"  name="email" id="inputEmail" class="form-control" placeholder="새 이메일" value="{{request.user.email}}" required>
             </p>
             <button class="btn btn-lg btn-primary btn-block" type="submit">업데이트</button>
      </form>

{%endblock %}

board/templates/board/user_update_success.html
{% extends './about_user.html' %}
{% block article%}
<h3 style="margin-top: 3rem;">업데이트가 완료되었습니다!</h3>
{%endblock %}